// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_wrapper_out_conv2mem_Pipeline_VITIS_LOOP_41_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        mul_i,
        zext_ln40,
        cmp31_i,
        mul_ln40,
        p_cast_i,
        memory_load,
        tmp_i_23,
        tmp_1_i,
        tmp_2_i,
        tmp_3_i,
        tmp_4_i,
        tmp_5_i,
        tmp_6_i,
        tmp_7_i,
        tmp_8_i,
        tmp_9_i,
        tmp_i,
        tmp_10_i,
        tmp_11_i,
        tmp_12_i,
        tmp_13_i,
        tmp_14_i,
        tmp_15_i,
        tmp_16_i,
        tmp_17_i,
        tmp_18_i,
        tmp_19_i,
        tmp_20_i,
        tmp_21_i,
        tmp_22_i,
        tmp_23_i,
        tmp_24_i,
        tmp_25_i,
        tmp_26_i,
        tmp_27_i,
        tmp_28_i,
        tmp_29_i,
        tmp_30_i,
        tmp_31_i,
        tmp_32_i,
        tmp_33_i,
        tmp_34_i,
        tmp_35_i,
        tmp_36_i,
        tmp_37_i,
        tmp_38_i,
        tmp_39_i,
        tmp_40_i,
        tmp_41_i,
        tmp_42_i,
        tmp_43_i,
        tmp_44_i,
        tmp_45_i,
        tmp_46_i,
        tmp_47_i,
        tmp_48_i,
        s_iw
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [63:0] m_axi_gmem1_0_WDATA;
output  [7:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [63:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [8:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [4:0] mul_i;
input  [3:0] zext_ln40;
input  [0:0] cmp31_i;
input  [36:0] mul_ln40;
input  [12:0] p_cast_i;
input  [63:0] memory_load;
input  [31:0] tmp_i_23;
input  [31:0] tmp_1_i;
input  [31:0] tmp_2_i;
input  [31:0] tmp_3_i;
input  [31:0] tmp_4_i;
input  [31:0] tmp_5_i;
input  [31:0] tmp_6_i;
input  [31:0] tmp_7_i;
input  [31:0] tmp_8_i;
input  [31:0] tmp_9_i;
input  [31:0] tmp_i;
input  [31:0] tmp_10_i;
input  [31:0] tmp_11_i;
input  [31:0] tmp_12_i;
input  [31:0] tmp_13_i;
input  [31:0] tmp_14_i;
input  [31:0] tmp_15_i;
input  [31:0] tmp_16_i;
input  [31:0] tmp_17_i;
input  [31:0] tmp_18_i;
input  [31:0] tmp_19_i;
input  [31:0] tmp_20_i;
input  [31:0] tmp_21_i;
input  [31:0] tmp_22_i;
input  [31:0] tmp_23_i;
input  [31:0] tmp_24_i;
input  [31:0] tmp_25_i;
input  [31:0] tmp_26_i;
input  [31:0] tmp_27_i;
input  [31:0] tmp_28_i;
input  [31:0] tmp_29_i;
input  [31:0] tmp_30_i;
input  [31:0] tmp_31_i;
input  [31:0] tmp_32_i;
input  [31:0] tmp_33_i;
input  [31:0] tmp_34_i;
input  [31:0] tmp_35_i;
input  [31:0] tmp_36_i;
input  [31:0] tmp_37_i;
input  [31:0] tmp_38_i;
input  [31:0] tmp_39_i;
input  [31:0] tmp_40_i;
input  [31:0] tmp_41_i;
input  [31:0] tmp_42_i;
input  [31:0] tmp_43_i;
input  [31:0] tmp_44_i;
input  [31:0] tmp_45_i;
input  [31:0] tmp_46_i;
input  [31:0] tmp_47_i;
input  [31:0] tmp_48_i;
input  [3:0] s_iw;

reg ap_idle;
reg m_axi_gmem1_0_AWVALID;
reg m_axi_gmem1_0_WVALID;
reg[63:0] m_axi_gmem1_0_WDATA;
reg m_axi_gmem1_0_BREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] brmerge_not_i_reg_1018;
reg   [0:0] brmerge_not_i_reg_1018_pp0_iter1_reg;
reg    ap_block_state4_io_grp2;
reg    ap_block_pp0_stage1_subdone_grp2_done_reg;
reg    ap_block_pp0_stage1_subdone_grp2;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage1_subdone_grp4_done_reg;
reg    ap_block_pp0_stage1_subdone_grp4;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln41_reg_1014;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_B;
wire    ap_block_pp0_stage1_grp4;
reg    gmem1_blk_n_AW;
wire    ap_block_pp0_stage0_grp1;
reg    gmem1_blk_n_W;
wire    ap_block_pp0_stage1_grp2;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] cmp46_i_fu_617_p2;
reg   [0:0] cmp46_i_reg_1003;
reg   [31:0] s_fw_4_reg_1008;
reg    ap_block_state5_io_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln41_fu_631_p2;
wire   [0:0] brmerge_not_i_fu_659_p2;
wire   [40:0] add_ln42_2_fu_695_p2;
reg   [40:0] add_ln42_2_reg_1022;
wire   [63:0] select_ln42_fu_701_p3;
reg   [63:0] select_ln42_reg_1027;
wire   [31:0] val_fu_709_p53;
reg   [31:0] val_reg_1032;
reg   [31:0] val_reg_1032_pp0_iter1_reg;
wire   [31:0] val_1_fu_817_p53;
reg   [31:0] val_1_reg_1037;
reg   [31:0] val_1_reg_1037_pp0_iter1_reg;
reg   [60:0] trunc_ln2_reg_1042;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
wire  signed [63:0] sext_ln42_2_fu_965_p1;
reg    ap_block_pp0_stage1_11001_grp4;
reg    ap_block_pp0_stage1_11001_grp2;
wire   [63:0] zext_ln51_fu_978_p1;
wire    ap_block_pp0_stage1_01001_grp2;
wire   [63:0] zext_ln51_1_fu_986_p1;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [31:0] s_fw_fu_240;
wire   [31:0] s_fw_7_fu_954_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_s_fw_4;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_grp0;
wire   [4:0] trunc_ln41_fu_637_p1;
wire   [31:0] zext_ln40_cast_fu_609_p1;
wire   [31:0] in_w_fu_647_p2;
wire   [0:0] cmp32_i_fu_653_p2;
wire   [32:0] shl_ln_fu_665_p3;
wire  signed [36:0] sext_ln42_fu_673_p1;
wire   [36:0] add_ln42_fu_677_p2;
wire   [39:0] tmp_fu_683_p3;
wire  signed [40:0] sext_ln42_1_fu_691_p1;
wire   [40:0] p_cast_i_cast_fu_613_p1;
wire   [31:0] val_fu_709_p51;
wire   [4:0] s_mem_i_fu_641_p2;
wire   [31:0] val_1_fu_817_p51;
wire    ap_block_pp0_stage1_grp0;
wire  signed [63:0] sext_ln42_3_fu_925_p1;
wire   [63:0] add_ln42_1_fu_928_p2;
wire   [31:0] s_fw_5_fu_943_p2;
wire   [31:0] s_fw_6_fu_948_p3;
wire  signed [44:0] sext_ln51_fu_975_p1;
wire  signed [44:0] sext_ln51_1_fu_983_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage1_11001;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_709;
reg    ap_condition_323;
wire   [4:0] val_fu_709_p1;
wire   [4:0] val_fu_709_p3;
wire   [4:0] val_fu_709_p5;
wire   [4:0] val_fu_709_p7;
wire   [4:0] val_fu_709_p9;
wire   [4:0] val_fu_709_p11;
wire   [4:0] val_fu_709_p13;
wire   [4:0] val_fu_709_p15;
wire   [4:0] val_fu_709_p17;
wire   [4:0] val_fu_709_p19;
wire   [4:0] val_fu_709_p21;
wire   [4:0] val_fu_709_p23;
wire   [4:0] val_fu_709_p25;
wire   [4:0] val_fu_709_p27;
wire   [4:0] val_fu_709_p29;
wire   [4:0] val_fu_709_p31;
wire  signed [4:0] val_fu_709_p33;
wire  signed [4:0] val_fu_709_p35;
wire  signed [4:0] val_fu_709_p37;
wire  signed [4:0] val_fu_709_p39;
wire  signed [4:0] val_fu_709_p41;
wire  signed [4:0] val_fu_709_p43;
wire  signed [4:0] val_fu_709_p45;
wire  signed [4:0] val_fu_709_p47;
wire  signed [4:0] val_fu_709_p49;
wire   [4:0] val_1_fu_817_p1;
wire   [4:0] val_1_fu_817_p3;
wire   [4:0] val_1_fu_817_p5;
wire   [4:0] val_1_fu_817_p7;
wire   [4:0] val_1_fu_817_p9;
wire   [4:0] val_1_fu_817_p11;
wire   [4:0] val_1_fu_817_p13;
wire   [4:0] val_1_fu_817_p15;
wire   [4:0] val_1_fu_817_p17;
wire   [4:0] val_1_fu_817_p19;
wire   [4:0] val_1_fu_817_p21;
wire   [4:0] val_1_fu_817_p23;
wire   [4:0] val_1_fu_817_p25;
wire   [4:0] val_1_fu_817_p27;
wire   [4:0] val_1_fu_817_p29;
wire   [4:0] val_1_fu_817_p31;
wire  signed [4:0] val_1_fu_817_p33;
wire  signed [4:0] val_1_fu_817_p35;
wire  signed [4:0] val_1_fu_817_p37;
wire  signed [4:0] val_1_fu_817_p39;
wire  signed [4:0] val_1_fu_817_p41;
wire  signed [4:0] val_1_fu_817_p43;
wire  signed [4:0] val_1_fu_817_p45;
wire  signed [4:0] val_1_fu_817_p47;
wire  signed [4:0] val_1_fu_817_p49;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp4_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 s_fw_fu_240 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) top_wrapper_sparsemux_51_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_51_5_32_1_1_U2006(
    .din0(tmp_i_23),
    .din1(tmp_1_i),
    .din2(tmp_2_i),
    .din3(tmp_3_i),
    .din4(tmp_4_i),
    .din5(tmp_5_i),
    .din6(tmp_6_i),
    .din7(tmp_7_i),
    .din8(tmp_8_i),
    .din9(tmp_9_i),
    .din10(tmp_i),
    .din11(tmp_10_i),
    .din12(tmp_11_i),
    .din13(tmp_12_i),
    .din14(tmp_13_i),
    .din15(tmp_14_i),
    .din16(tmp_15_i),
    .din17(tmp_16_i),
    .din18(tmp_17_i),
    .din19(tmp_18_i),
    .din20(tmp_19_i),
    .din21(tmp_20_i),
    .din22(tmp_21_i),
    .din23(tmp_22_i),
    .din24(tmp_23_i),
    .def(val_fu_709_p51),
    .sel(s_mem_i_fu_641_p2),
    .dout(val_fu_709_p53)
);

(* dissolve_hierarchy = "yes" *) top_wrapper_sparsemux_51_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_51_5_32_1_1_U2007(
    .din0(tmp_24_i),
    .din1(tmp_25_i),
    .din2(tmp_26_i),
    .din3(tmp_27_i),
    .din4(tmp_28_i),
    .din5(tmp_29_i),
    .din6(tmp_30_i),
    .din7(tmp_31_i),
    .din8(tmp_32_i),
    .din9(tmp_33_i),
    .din10(tmp_34_i),
    .din11(tmp_35_i),
    .din12(tmp_36_i),
    .din13(tmp_37_i),
    .din14(tmp_38_i),
    .din15(tmp_39_i),
    .din16(tmp_40_i),
    .din17(tmp_41_i),
    .din18(tmp_42_i),
    .din19(tmp_43_i),
    .din20(tmp_44_i),
    .din21(tmp_45_i),
    .din22(tmp_46_i),
    .din23(tmp_47_i),
    .din24(tmp_48_i),
    .def(val_1_fu_817_p51),
    .sel(s_mem_i_fu_641_p2),
    .dout(val_1_fu_817_p53)
);

top_wrapper_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp2)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp4)) begin
                ap_block_pp0_stage1_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        s_fw_fu_240 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln41_reg_1014 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        s_fw_fu_240 <= s_fw_7_fu_954_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln42_2_reg_1022 <= add_ln42_2_fu_695_p2;
        brmerge_not_i_reg_1018 <= brmerge_not_i_fu_659_p2;
        brmerge_not_i_reg_1018_pp0_iter1_reg <= brmerge_not_i_reg_1018;
        icmp_ln41_reg_1014 <= icmp_ln41_fu_631_p2;
        s_fw_4_reg_1008 <= ap_sig_allocacmp_s_fw_4;
        select_ln42_reg_1027[1] <= select_ln42_fu_701_p3[1];
        val_1_reg_1037 <= val_1_fu_817_p53;
        val_1_reg_1037_pp0_iter1_reg <= val_1_reg_1037;
        val_reg_1032 <= val_fu_709_p53;
        val_reg_1032_pp0_iter1_reg <= val_reg_1032;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        cmp46_i_reg_1003 <= cmp46_i_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        trunc_ln2_reg_1042 <= {{add_ln42_1_fu_928_p2[63:3]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln41_reg_1014 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_s_fw_4 = 32'd0;
    end else begin
        ap_sig_allocacmp_s_fw_4 = s_fw_fu_240;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem1_blk_n_AW = m_axi_gmem1_0_AWREADY;
    end else begin
        gmem1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp4) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg))) begin
        gmem1_blk_n_B = m_axi_gmem1_0_BVALID;
    end else begin
        gmem1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((brmerge_not_i_reg_1018_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((brmerge_not_i_reg_1018_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)))) begin
        gmem1_blk_n_W = m_axi_gmem1_0_WREADY;
    end else begin
        gmem1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem1_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp4) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg))) begin
        m_axi_gmem1_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem1_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((brmerge_not_i_reg_1018_pp0_iter1_reg == 1'd1)) begin
        if ((1'b1 == ap_condition_323)) begin
            m_axi_gmem1_0_WDATA = zext_ln51_1_fu_986_p1;
        end else if ((1'b1 == ap_condition_709)) begin
            m_axi_gmem1_0_WDATA = zext_ln51_fu_978_p1;
        end else begin
            m_axi_gmem1_0_WDATA = 'bx;
        end
    end else begin
        m_axi_gmem1_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((brmerge_not_i_reg_1018_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((brmerge_not_i_reg_1018_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)))) begin
        m_axi_gmem1_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_1_fu_928_p2 = ($signed(sext_ln42_3_fu_925_p1) + $signed(memory_load));

assign add_ln42_2_fu_695_p2 = ($signed(sext_ln42_1_fu_691_p1) + $signed(p_cast_i_cast_fu_613_p1));

assign add_ln42_fu_677_p2 = ($signed(mul_ln40) + $signed(sext_ln42_fu_673_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem1_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((m_axi_gmem1_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem1_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((m_axi_gmem1_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp4 = ((m_axi_gmem1_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((m_axi_gmem1_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp4 = ((m_axi_gmem1_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_state4_io_grp2 = ((brmerge_not_i_reg_1018_pp0_iter1_reg == 1'd1) & (m_axi_gmem1_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_io_grp1 = ((brmerge_not_i_reg_1018_pp0_iter1_reg == 1'd1) & (m_axi_gmem1_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_condition_323 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001_grp1));
end

always @ (*) begin
    ap_condition_709 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign brmerge_not_i_fu_659_p2 = (cmp32_i_fu_653_p2 & cmp31_i);

assign cmp32_i_fu_653_p2 = (($signed(in_w_fu_647_p2) < $signed(32'd13)) ? 1'b1 : 1'b0);

assign cmp46_i_fu_617_p2 = ((s_iw > 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_631_p2 = (($signed(ap_sig_allocacmp_s_fw_4) < $signed(32'd5)) ? 1'b1 : 1'b0);

assign in_w_fu_647_p2 = (ap_sig_allocacmp_s_fw_4 + zext_ln40_cast_fu_609_p1);

assign m_axi_gmem1_0_ARADDR = 64'd0;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 32'd0;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_ARVALID = 1'b0;

assign m_axi_gmem1_0_AWADDR = sext_ln42_2_fu_965_p1;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = select_ln42_reg_1027;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_RREADY = 1'b0;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WSTRB = 8'd255;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign p_cast_i_cast_fu_613_p1 = p_cast_i;

assign s_fw_5_fu_943_p2 = (s_fw_4_reg_1008 + 32'd5);

assign s_fw_6_fu_948_p3 = ((cmp46_i_reg_1003[0:0] == 1'b1) ? s_fw_5_fu_943_p2 : s_fw_4_reg_1008);

assign s_fw_7_fu_954_p2 = (s_fw_6_fu_948_p3 + 32'd1);

assign s_mem_i_fu_641_p2 = (trunc_ln41_fu_637_p1 + mul_i);

assign select_ln42_fu_701_p3 = ((brmerge_not_i_fu_659_p2[0:0] == 1'b1) ? 64'd2 : 64'd0);

assign sext_ln42_1_fu_691_p1 = $signed(tmp_fu_683_p3);

assign sext_ln42_2_fu_965_p1 = $signed(trunc_ln2_reg_1042);

assign sext_ln42_3_fu_925_p1 = $signed(add_ln42_2_reg_1022);

assign sext_ln42_fu_673_p1 = $signed(shl_ln_fu_665_p3);

assign sext_ln51_1_fu_983_p1 = $signed(val_1_reg_1037_pp0_iter1_reg);

assign sext_ln51_fu_975_p1 = $signed(val_reg_1032_pp0_iter1_reg);

assign shl_ln_fu_665_p3 = {{in_w_fu_647_p2}, {1'd0}};

assign tmp_fu_683_p3 = {{add_ln42_fu_677_p2}, {3'd0}};

assign trunc_ln41_fu_637_p1 = ap_sig_allocacmp_s_fw_4[4:0];

assign val_1_fu_817_p51 = 'bx;

assign val_fu_709_p51 = 'bx;

assign zext_ln40_cast_fu_609_p1 = zext_ln40;

assign zext_ln51_1_fu_986_p1 = $unsigned(sext_ln51_1_fu_983_p1);

assign zext_ln51_fu_978_p1 = $unsigned(sext_ln51_fu_975_p1);

always @ (posedge ap_clk) begin
    select_ln42_reg_1027[0] <= 1'b0;
    select_ln42_reg_1027[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //top_wrapper_out_conv2mem_Pipeline_VITIS_LOOP_41_4
