// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_wrapper_conv_Pipeline_VITIS_LOOP_41_1_VITIS_LOOP_42_2_VITIS_LOOP_43_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        filter2conv_dout,
        filter2conv_empty_n,
        filter2conv_read,
        filter2conv_num_data_valid,
        filter2conv_fifo_cap,
        filter_mem_17,
        filter_mem_16,
        filter_mem_15,
        filter_mem_14,
        filter_mem_13,
        filter_mem_12,
        filter_mem_11,
        filter_mem_10,
        filter_mem_9,
        filter_mem_8,
        filter_mem_7,
        filter_mem_6,
        filter_mem_5,
        filter_mem_4,
        filter_mem_3,
        filter_mem_2,
        filter_mem_1,
        filter_mem,
        filter_mem_35_out,
        filter_mem_35_out_ap_vld,
        filter_mem_34_out,
        filter_mem_34_out_ap_vld,
        filter_mem_33_out,
        filter_mem_33_out_ap_vld,
        filter_mem_32_out,
        filter_mem_32_out_ap_vld,
        filter_mem_31_out,
        filter_mem_31_out_ap_vld,
        filter_mem_30_out,
        filter_mem_30_out_ap_vld,
        filter_mem_29_out,
        filter_mem_29_out_ap_vld,
        filter_mem_28_out,
        filter_mem_28_out_ap_vld,
        filter_mem_27_out,
        filter_mem_27_out_ap_vld,
        filter_mem_26_out,
        filter_mem_26_out_ap_vld,
        filter_mem_25_out,
        filter_mem_25_out_ap_vld,
        filter_mem_24_out,
        filter_mem_24_out_ap_vld,
        filter_mem_23_out,
        filter_mem_23_out_ap_vld,
        filter_mem_22_out,
        filter_mem_22_out_ap_vld,
        filter_mem_21_out,
        filter_mem_21_out_ap_vld,
        filter_mem_20_out,
        filter_mem_20_out_ap_vld,
        filter_mem_19_out,
        filter_mem_19_out_ap_vld,
        filter_mem_18_out,
        filter_mem_18_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] filter2conv_dout;
input   filter2conv_empty_n;
output   filter2conv_read;
input  [7:0] filter2conv_num_data_valid;
input  [7:0] filter2conv_fifo_cap;
input  [7:0] filter_mem_17;
input  [7:0] filter_mem_16;
input  [7:0] filter_mem_15;
input  [7:0] filter_mem_14;
input  [7:0] filter_mem_13;
input  [7:0] filter_mem_12;
input  [7:0] filter_mem_11;
input  [7:0] filter_mem_10;
input  [7:0] filter_mem_9;
input  [7:0] filter_mem_8;
input  [7:0] filter_mem_7;
input  [7:0] filter_mem_6;
input  [7:0] filter_mem_5;
input  [7:0] filter_mem_4;
input  [7:0] filter_mem_3;
input  [7:0] filter_mem_2;
input  [7:0] filter_mem_1;
input  [7:0] filter_mem;
output  [7:0] filter_mem_35_out;
output   filter_mem_35_out_ap_vld;
output  [7:0] filter_mem_34_out;
output   filter_mem_34_out_ap_vld;
output  [7:0] filter_mem_33_out;
output   filter_mem_33_out_ap_vld;
output  [7:0] filter_mem_32_out;
output   filter_mem_32_out_ap_vld;
output  [7:0] filter_mem_31_out;
output   filter_mem_31_out_ap_vld;
output  [7:0] filter_mem_30_out;
output   filter_mem_30_out_ap_vld;
output  [7:0] filter_mem_29_out;
output   filter_mem_29_out_ap_vld;
output  [7:0] filter_mem_28_out;
output   filter_mem_28_out_ap_vld;
output  [7:0] filter_mem_27_out;
output   filter_mem_27_out_ap_vld;
output  [7:0] filter_mem_26_out;
output   filter_mem_26_out_ap_vld;
output  [7:0] filter_mem_25_out;
output   filter_mem_25_out_ap_vld;
output  [7:0] filter_mem_24_out;
output   filter_mem_24_out_ap_vld;
output  [7:0] filter_mem_23_out;
output   filter_mem_23_out_ap_vld;
output  [7:0] filter_mem_22_out;
output   filter_mem_22_out_ap_vld;
output  [7:0] filter_mem_21_out;
output   filter_mem_21_out_ap_vld;
output  [7:0] filter_mem_20_out;
output   filter_mem_20_out_ap_vld;
output  [7:0] filter_mem_19_out;
output   filter_mem_19_out_ap_vld;
output  [7:0] filter_mem_18_out;
output   filter_mem_18_out_ap_vld;

reg ap_idle;
reg filter2conv_read;
reg filter_mem_35_out_ap_vld;
reg filter_mem_34_out_ap_vld;
reg filter_mem_33_out_ap_vld;
reg filter_mem_32_out_ap_vld;
reg filter_mem_31_out_ap_vld;
reg filter_mem_30_out_ap_vld;
reg filter_mem_29_out_ap_vld;
reg filter_mem_28_out_ap_vld;
reg filter_mem_27_out_ap_vld;
reg filter_mem_26_out_ap_vld;
reg filter_mem_25_out_ap_vld;
reg filter_mem_24_out_ap_vld;
reg filter_mem_23_out_ap_vld;
reg filter_mem_22_out_ap_vld;
reg filter_mem_21_out_ap_vld;
reg filter_mem_20_out_ap_vld;
reg filter_mem_19_out_ap_vld;
reg filter_mem_18_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_587_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    filter2conv_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [0:0] icmp_ln42_fu_599_p2;
reg   [0:0] icmp_ln42_reg_1299;
reg    ap_block_pp0_stage0_11001;
reg   [1:0] idx_depth_fu_134;
wire   [1:0] add_ln43_fu_1024_p2;
reg    ap_block_pp0_stage0_11001_grp1;
wire    ap_loop_init;
reg   [1:0] s_fw_fu_138;
wire   [1:0] select_ln42_fu_694_p3;
reg   [3:0] indvar_flatten_fu_142;
wire   [3:0] select_ln42_1_fu_611_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg   [1:0] s_fh_fu_146;
wire   [1:0] select_ln41_fu_668_p3;
reg   [4:0] indvar_flatten48_fu_150;
wire   [4:0] add_ln41_1_fu_593_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten48_load;
reg   [7:0] filter_mem_18_fu_154;
wire   [7:0] select_ln48_3_fu_974_p3;
wire   [3:0] empty_48_fu_724_p2;
reg   [7:0] filter_mem_19_fu_158;
wire   [7:0] select_ln48_2_fu_966_p3;
reg   [7:0] filter_mem_20_fu_162;
wire   [7:0] select_ln48_5_fu_942_p3;
reg   [7:0] filter_mem_21_fu_166;
wire   [7:0] select_ln48_4_fu_934_p3;
reg   [7:0] filter_mem_22_fu_170;
wire   [7:0] select_ln48_7_fu_910_p3;
reg   [7:0] filter_mem_23_fu_174;
wire   [7:0] select_ln48_6_fu_902_p3;
reg   [7:0] filter_mem_24_fu_178;
wire   [7:0] select_ln48_9_fu_878_p3;
reg   [7:0] filter_mem_25_fu_182;
wire   [7:0] select_ln48_8_fu_870_p3;
reg   [7:0] filter_mem_26_fu_186;
wire   [7:0] select_ln48_11_fu_846_p3;
reg   [7:0] filter_mem_27_fu_190;
wire   [7:0] select_ln48_10_fu_838_p3;
reg   [7:0] filter_mem_28_fu_194;
wire   [7:0] select_ln48_13_fu_814_p3;
reg   [7:0] filter_mem_29_fu_198;
wire   [7:0] select_ln48_12_fu_806_p3;
reg   [7:0] filter_mem_30_fu_202;
wire   [7:0] select_ln48_15_fu_782_p3;
reg   [7:0] filter_mem_31_fu_206;
wire   [7:0] select_ln48_14_fu_774_p3;
reg   [7:0] filter_mem_32_fu_210;
wire   [7:0] select_ln48_17_fu_750_p3;
reg   [7:0] filter_mem_33_fu_214;
wire   [7:0] select_ln48_16_fu_742_p3;
reg   [7:0] filter_mem_34_fu_218;
wire   [7:0] select_ln48_1_fu_1006_p3;
reg   [7:0] filter_mem_35_fu_222;
wire   [7:0] select_ln48_fu_998_p3;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [3:0] add_ln42_3_fu_605_p2;
wire   [0:0] icmp_ln43_fu_656_p2;
wire   [0:0] xor_ln36_fu_651_p2;
wire   [1:0] add_ln41_fu_638_p2;
wire   [1:0] select_ln36_fu_644_p3;
wire   [0:0] and_ln36_fu_662_p2;
wire   [0:0] empty_fu_681_p2;
wire   [1:0] add_ln42_fu_675_p2;
wire   [3:0] p_shl_fu_706_p3;
wire   [3:0] zext_ln41_fu_702_p1;
wire   [3:0] empty_47_fu_714_p2;
wire   [3:0] zext_ln42_fu_720_p1;
wire   [1:0] s_ich_mid2_fu_686_p3;
wire   [0:0] icmp_ln48_fu_730_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_561;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 idx_depth_fu_134 = 2'd0;
#0 s_fw_fu_138 = 2'd0;
#0 indvar_flatten_fu_142 = 4'd0;
#0 s_fh_fu_146 = 2'd0;
#0 indvar_flatten48_fu_150 = 5'd0;
#0 filter_mem_18_fu_154 = 8'd0;
#0 filter_mem_19_fu_158 = 8'd0;
#0 filter_mem_20_fu_162 = 8'd0;
#0 filter_mem_21_fu_166 = 8'd0;
#0 filter_mem_22_fu_170 = 8'd0;
#0 filter_mem_23_fu_174 = 8'd0;
#0 filter_mem_24_fu_178 = 8'd0;
#0 filter_mem_25_fu_182 = 8'd0;
#0 filter_mem_26_fu_186 = 8'd0;
#0 filter_mem_27_fu_190 = 8'd0;
#0 filter_mem_28_fu_194 = 8'd0;
#0 filter_mem_29_fu_198 = 8'd0;
#0 filter_mem_30_fu_202 = 8'd0;
#0 filter_mem_31_fu_206 = 8'd0;
#0 filter_mem_32_fu_210 = 8'd0;
#0 filter_mem_33_fu_214 = 8'd0;
#0 filter_mem_34_fu_218 = 8'd0;
#0 filter_mem_35_fu_222 = 8'd0;
#0 ap_done_reg = 1'b0;
end

top_wrapper_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_18_fu_154 <= filter_mem;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd0))) begin
            filter_mem_18_fu_154 <= select_ln48_3_fu_974_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_19_fu_158 <= filter_mem_1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd0))) begin
            filter_mem_19_fu_158 <= select_ln48_2_fu_966_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_20_fu_162 <= filter_mem_2;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd1))) begin
            filter_mem_20_fu_162 <= select_ln48_5_fu_942_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_21_fu_166 <= filter_mem_3;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd1))) begin
            filter_mem_21_fu_166 <= select_ln48_4_fu_934_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_22_fu_170 <= filter_mem_4;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd2))) begin
            filter_mem_22_fu_170 <= select_ln48_7_fu_910_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_23_fu_174 <= filter_mem_5;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd2))) begin
            filter_mem_23_fu_174 <= select_ln48_6_fu_902_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_24_fu_178 <= filter_mem_6;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd3))) begin
            filter_mem_24_fu_178 <= select_ln48_9_fu_878_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_25_fu_182 <= filter_mem_7;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd3))) begin
            filter_mem_25_fu_182 <= select_ln48_8_fu_870_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_26_fu_186 <= filter_mem_8;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd4))) begin
            filter_mem_26_fu_186 <= select_ln48_11_fu_846_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_27_fu_190 <= filter_mem_9;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd4))) begin
            filter_mem_27_fu_190 <= select_ln48_10_fu_838_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_28_fu_194 <= filter_mem_10;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd5))) begin
            filter_mem_28_fu_194 <= select_ln48_13_fu_814_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_29_fu_198 <= filter_mem_11;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd5))) begin
            filter_mem_29_fu_198 <= select_ln48_12_fu_806_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_30_fu_202 <= filter_mem_12;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd6))) begin
            filter_mem_30_fu_202 <= select_ln48_15_fu_782_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_31_fu_206 <= filter_mem_13;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd6))) begin
            filter_mem_31_fu_206 <= select_ln48_14_fu_774_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_32_fu_210 <= filter_mem_14;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd7))) begin
            filter_mem_32_fu_210 <= select_ln48_17_fu_750_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_33_fu_214 <= filter_mem_15;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (empty_48_fu_724_p2 == 4'd7))) begin
            filter_mem_33_fu_214 <= select_ln48_16_fu_742_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_34_fu_218 <= filter_mem_16;
        end else if ((1'b1 == ap_condition_561)) begin
            filter_mem_34_fu_218 <= select_ln48_1_fu_1006_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            filter_mem_35_fu_222 <= filter_mem_17;
        end else if ((1'b1 == ap_condition_561)) begin
            filter_mem_35_fu_222 <= select_ln48_fu_998_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_depth_fu_134 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            idx_depth_fu_134 <= add_ln43_fu_1024_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_587_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten48_fu_150 <= add_ln41_1_fu_593_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten48_fu_150 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_587_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_142 <= select_ln42_1_fu_611_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_142 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s_fh_fu_146 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            s_fh_fu_146 <= select_ln41_fu_668_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s_fw_fu_138 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            s_fw_fu_138 <= select_ln42_fu_694_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln42_reg_1299 <= icmp_ln42_fu_599_p2;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten48_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten48_load = indvar_flatten48_fu_150;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_142;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter2conv_blk_n = filter2conv_empty_n;
    end else begin
        filter2conv_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter2conv_read = 1'b1;
    end else begin
        filter2conv_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_18_out_ap_vld = 1'b1;
    end else begin
        filter_mem_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_19_out_ap_vld = 1'b1;
    end else begin
        filter_mem_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_20_out_ap_vld = 1'b1;
    end else begin
        filter_mem_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_21_out_ap_vld = 1'b1;
    end else begin
        filter_mem_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_22_out_ap_vld = 1'b1;
    end else begin
        filter_mem_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_23_out_ap_vld = 1'b1;
    end else begin
        filter_mem_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_24_out_ap_vld = 1'b1;
    end else begin
        filter_mem_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_25_out_ap_vld = 1'b1;
    end else begin
        filter_mem_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_26_out_ap_vld = 1'b1;
    end else begin
        filter_mem_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_27_out_ap_vld = 1'b1;
    end else begin
        filter_mem_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_28_out_ap_vld = 1'b1;
    end else begin
        filter_mem_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_29_out_ap_vld = 1'b1;
    end else begin
        filter_mem_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_30_out_ap_vld = 1'b1;
    end else begin
        filter_mem_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_31_out_ap_vld = 1'b1;
    end else begin
        filter_mem_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_32_out_ap_vld = 1'b1;
    end else begin
        filter_mem_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_33_out_ap_vld = 1'b1;
    end else begin
        filter_mem_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_34_out_ap_vld = 1'b1;
    end else begin
        filter_mem_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln41_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_mem_35_out_ap_vld = 1'b1;
    end else begin
        filter_mem_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln41_1_fu_593_p2 = (ap_sig_allocacmp_indvar_flatten48_load + 5'd1);

assign add_ln41_fu_638_p2 = (s_fh_fu_146 + 2'd1);

assign add_ln42_3_fu_605_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln42_fu_675_p2 = (select_ln36_fu_644_p3 + 2'd1);

assign add_ln43_fu_1024_p2 = (s_ich_mid2_fu_686_p3 + 2'd1);

assign and_ln36_fu_662_p2 = (xor_ln36_fu_651_p2 & icmp_ln43_fu_656_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((filter2conv_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((filter2conv_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((filter2conv_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((filter2conv_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_561 = (~(empty_48_fu_724_p2 == 4'd7) & ~(empty_48_fu_724_p2 == 4'd6) & ~(empty_48_fu_724_p2 == 4'd5) & ~(empty_48_fu_724_p2 == 4'd4) & ~(empty_48_fu_724_p2 == 4'd3) & ~(empty_48_fu_724_p2 == 4'd2) & ~(empty_48_fu_724_p2 == 4'd1) & ~(empty_48_fu_724_p2 == 4'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_47_fu_714_p2 = (p_shl_fu_706_p3 - zext_ln41_fu_702_p1);

assign empty_48_fu_724_p2 = (empty_47_fu_714_p2 + zext_ln42_fu_720_p1);

assign empty_fu_681_p2 = (icmp_ln42_reg_1299 | and_ln36_fu_662_p2);

assign filter_mem_18_out = filter_mem_18_fu_154;

assign filter_mem_19_out = filter_mem_19_fu_158;

assign filter_mem_20_out = filter_mem_20_fu_162;

assign filter_mem_21_out = filter_mem_21_fu_166;

assign filter_mem_22_out = filter_mem_22_fu_170;

assign filter_mem_23_out = filter_mem_23_fu_174;

assign filter_mem_24_out = filter_mem_24_fu_178;

assign filter_mem_25_out = filter_mem_25_fu_182;

assign filter_mem_26_out = filter_mem_26_fu_186;

assign filter_mem_27_out = filter_mem_27_fu_190;

assign filter_mem_28_out = filter_mem_28_fu_194;

assign filter_mem_29_out = filter_mem_29_fu_198;

assign filter_mem_30_out = filter_mem_30_fu_202;

assign filter_mem_31_out = filter_mem_31_fu_206;

assign filter_mem_32_out = filter_mem_32_fu_210;

assign filter_mem_33_out = filter_mem_33_fu_214;

assign filter_mem_34_out = filter_mem_34_fu_218;

assign filter_mem_35_out = filter_mem_35_fu_222;

assign icmp_ln41_fu_587_p2 = ((ap_sig_allocacmp_indvar_flatten48_load == 5'd18) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_599_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_656_p2 = ((idx_depth_fu_134 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_730_p2 = ((s_ich_mid2_fu_686_p3 == 2'd0) ? 1'b1 : 1'b0);

assign p_shl_fu_706_p3 = {{select_ln41_fu_668_p3}, {2'd0}};

assign s_ich_mid2_fu_686_p3 = ((empty_fu_681_p2[0:0] == 1'b1) ? 2'd0 : idx_depth_fu_134);

assign select_ln36_fu_644_p3 = ((icmp_ln42_reg_1299[0:0] == 1'b1) ? 2'd0 : s_fw_fu_138);

assign select_ln41_fu_668_p3 = ((icmp_ln42_reg_1299[0:0] == 1'b1) ? add_ln41_fu_638_p2 : s_fh_fu_146);

assign select_ln42_1_fu_611_p3 = ((icmp_ln42_fu_599_p2[0:0] == 1'b1) ? 4'd1 : add_ln42_3_fu_605_p2);

assign select_ln42_fu_694_p3 = ((and_ln36_fu_662_p2[0:0] == 1'b1) ? add_ln42_fu_675_p2 : select_ln36_fu_644_p3);

assign select_ln48_10_fu_838_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_27_fu_190 : filter2conv_dout);

assign select_ln48_11_fu_846_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_26_fu_186);

assign select_ln48_12_fu_806_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_29_fu_198 : filter2conv_dout);

assign select_ln48_13_fu_814_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_28_fu_194);

assign select_ln48_14_fu_774_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_31_fu_206 : filter2conv_dout);

assign select_ln48_15_fu_782_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_30_fu_202);

assign select_ln48_16_fu_742_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_33_fu_214 : filter2conv_dout);

assign select_ln48_17_fu_750_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_32_fu_210);

assign select_ln48_1_fu_1006_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_34_fu_218);

assign select_ln48_2_fu_966_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_19_fu_158 : filter2conv_dout);

assign select_ln48_3_fu_974_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_18_fu_154);

assign select_ln48_4_fu_934_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_21_fu_166 : filter2conv_dout);

assign select_ln48_5_fu_942_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_20_fu_162);

assign select_ln48_6_fu_902_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_23_fu_174 : filter2conv_dout);

assign select_ln48_7_fu_910_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_22_fu_170);

assign select_ln48_8_fu_870_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_25_fu_182 : filter2conv_dout);

assign select_ln48_9_fu_878_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter2conv_dout : filter_mem_24_fu_178);

assign select_ln48_fu_998_p3 = ((icmp_ln48_fu_730_p2[0:0] == 1'b1) ? filter_mem_35_fu_222 : filter2conv_dout);

assign xor_ln36_fu_651_p2 = (icmp_ln42_reg_1299 ^ 1'd1);

assign zext_ln41_fu_702_p1 = select_ln41_fu_668_p3;

assign zext_ln42_fu_720_p1 = select_ln42_fu_694_p3;

endmodule //top_wrapper_conv_Pipeline_VITIS_LOOP_41_1_VITIS_LOOP_42_2_VITIS_LOOP_43_3
