-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_wrapper_out_conv2mem_Pipeline_VITIS_LOOP_41_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_WREADY : IN STD_LOGIC;
    m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RVALID : IN STD_LOGIC;
    m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_RLAST : IN STD_LOGIC;
    m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BVALID : IN STD_LOGIC;
    m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mul_i : IN STD_LOGIC_VECTOR (4 downto 0);
    zext_ln40 : IN STD_LOGIC_VECTOR (3 downto 0);
    cmp31_i : IN STD_LOGIC_VECTOR (0 downto 0);
    mul_ln40 : IN STD_LOGIC_VECTOR (36 downto 0);
    p_cast_i : IN STD_LOGIC_VECTOR (12 downto 0);
    memory_load : IN STD_LOGIC_VECTOR (63 downto 0);
    tmp_i_23 : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_3_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_4_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_5_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_6_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_7_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_8_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_9_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_10_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_11_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_12_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_13_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_14_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_15_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_16_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_17_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_18_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_19_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_20_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_21_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_22_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_23_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_24_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_25_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_26_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_27_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_28_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_29_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_30_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_31_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_32_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_33_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_34_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_35_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_36_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_37_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_38_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_39_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_40_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_41_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_42_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_43_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_44_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_45_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_46_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_47_i : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_48_i : IN STD_LOGIC_VECTOR (31 downto 0);
    s_iw : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of top_wrapper_out_conv2mem_Pipeline_VITIS_LOOP_41_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal brmerge_not_i_reg_1018 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_not_i_reg_1018_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_io_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp4 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln41_reg_1014 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage1_grp4 : BOOLEAN;
    signal gmem1_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem1_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal cmp46_i_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp46_i_reg_1003 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_fw_4_reg_1008 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state5_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln41_fu_631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_not_i_fu_659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln42_2_fu_695_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal add_ln42_2_reg_1022 : STD_LOGIC_VECTOR (40 downto 0);
    signal select_ln42_fu_701_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln42_reg_1027 : STD_LOGIC_VECTOR (63 downto 0);
    signal val_fu_709_p53 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_1032 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_1032_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal val_1_fu_817_p53 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_1_reg_1037 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_1_reg_1037_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln2_reg_1042 : STD_LOGIC_VECTOR (60 downto 0);
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal sext_ln42_2_fu_965_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp2 : BOOLEAN;
    signal zext_ln51_fu_978_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1_01001_grp2 : BOOLEAN;
    signal zext_ln51_1_fu_986_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal s_fw_fu_240 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal s_fw_7_fu_954_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_s_fw_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal trunc_ln41_fu_637_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln40_cast_fu_609_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_w_fu_647_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cmp32_i_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_665_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln42_fu_673_p1 : STD_LOGIC_VECTOR (36 downto 0);
    signal add_ln42_fu_677_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal tmp_fu_683_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln42_1_fu_691_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_cast_i_cast_fu_613_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal val_fu_709_p51 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_mem_i_fu_641_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p51 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_grp0 : BOOLEAN;
    signal sext_ln42_3_fu_925_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln42_1_fu_928_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal s_fw_5_fu_943_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal s_fw_6_fu_948_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln51_fu_975_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal sext_ln51_1_fu_983_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to4 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_709 : BOOLEAN;
    signal ap_condition_323 : BOOLEAN;
    signal val_fu_709_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_fu_709_p49 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_1_fu_817_p49 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_wrapper_sparsemux_51_5_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (4 downto 0);
        din24_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_wrapper_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_51_5_32_1_1_U2006 : component top_wrapper_sparsemux_51_5_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 32,
        CASE1 => "00001",
        din1_WIDTH => 32,
        CASE2 => "00010",
        din2_WIDTH => 32,
        CASE3 => "00011",
        din3_WIDTH => 32,
        CASE4 => "00100",
        din4_WIDTH => 32,
        CASE5 => "00101",
        din5_WIDTH => 32,
        CASE6 => "00110",
        din6_WIDTH => 32,
        CASE7 => "00111",
        din7_WIDTH => 32,
        CASE8 => "01000",
        din8_WIDTH => 32,
        CASE9 => "01001",
        din9_WIDTH => 32,
        CASE10 => "01010",
        din10_WIDTH => 32,
        CASE11 => "01011",
        din11_WIDTH => 32,
        CASE12 => "01100",
        din12_WIDTH => 32,
        CASE13 => "01101",
        din13_WIDTH => 32,
        CASE14 => "01110",
        din14_WIDTH => 32,
        CASE15 => "01111",
        din15_WIDTH => 32,
        CASE16 => "10000",
        din16_WIDTH => 32,
        CASE17 => "10001",
        din17_WIDTH => 32,
        CASE18 => "10010",
        din18_WIDTH => 32,
        CASE19 => "10011",
        din19_WIDTH => 32,
        CASE20 => "10100",
        din20_WIDTH => 32,
        CASE21 => "10101",
        din21_WIDTH => 32,
        CASE22 => "10110",
        din22_WIDTH => 32,
        CASE23 => "10111",
        din23_WIDTH => 32,
        CASE24 => "11000",
        din24_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 5,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_i_23,
        din1 => tmp_1_i,
        din2 => tmp_2_i,
        din3 => tmp_3_i,
        din4 => tmp_4_i,
        din5 => tmp_5_i,
        din6 => tmp_6_i,
        din7 => tmp_7_i,
        din8 => tmp_8_i,
        din9 => tmp_9_i,
        din10 => tmp_i,
        din11 => tmp_10_i,
        din12 => tmp_11_i,
        din13 => tmp_12_i,
        din14 => tmp_13_i,
        din15 => tmp_14_i,
        din16 => tmp_15_i,
        din17 => tmp_16_i,
        din18 => tmp_17_i,
        din19 => tmp_18_i,
        din20 => tmp_19_i,
        din21 => tmp_20_i,
        din22 => tmp_21_i,
        din23 => tmp_22_i,
        din24 => tmp_23_i,
        def => val_fu_709_p51,
        sel => s_mem_i_fu_641_p2,
        dout => val_fu_709_p53);

    sparsemux_51_5_32_1_1_U2007 : component top_wrapper_sparsemux_51_5_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 32,
        CASE1 => "00001",
        din1_WIDTH => 32,
        CASE2 => "00010",
        din2_WIDTH => 32,
        CASE3 => "00011",
        din3_WIDTH => 32,
        CASE4 => "00100",
        din4_WIDTH => 32,
        CASE5 => "00101",
        din5_WIDTH => 32,
        CASE6 => "00110",
        din6_WIDTH => 32,
        CASE7 => "00111",
        din7_WIDTH => 32,
        CASE8 => "01000",
        din8_WIDTH => 32,
        CASE9 => "01001",
        din9_WIDTH => 32,
        CASE10 => "01010",
        din10_WIDTH => 32,
        CASE11 => "01011",
        din11_WIDTH => 32,
        CASE12 => "01100",
        din12_WIDTH => 32,
        CASE13 => "01101",
        din13_WIDTH => 32,
        CASE14 => "01110",
        din14_WIDTH => 32,
        CASE15 => "01111",
        din15_WIDTH => 32,
        CASE16 => "10000",
        din16_WIDTH => 32,
        CASE17 => "10001",
        din17_WIDTH => 32,
        CASE18 => "10010",
        din18_WIDTH => 32,
        CASE19 => "10011",
        din19_WIDTH => 32,
        CASE20 => "10100",
        din20_WIDTH => 32,
        CASE21 => "10101",
        din21_WIDTH => 32,
        CASE22 => "10110",
        din22_WIDTH => 32,
        CASE23 => "10111",
        din23_WIDTH => 32,
        CASE24 => "11000",
        din24_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 5,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_24_i,
        din1 => tmp_25_i,
        din2 => tmp_26_i,
        din3 => tmp_27_i,
        din4 => tmp_28_i,
        din5 => tmp_29_i,
        din6 => tmp_30_i,
        din7 => tmp_31_i,
        din8 => tmp_32_i,
        din9 => tmp_33_i,
        din10 => tmp_34_i,
        din11 => tmp_35_i,
        din12 => tmp_36_i,
        din13 => tmp_37_i,
        din14 => tmp_38_i,
        din15 => tmp_39_i,
        din16 => tmp_40_i,
        din17 => tmp_41_i,
        din18 => tmp_42_i,
        din19 => tmp_43_i,
        din20 => tmp_44_i,
        din21 => tmp_45_i,
        din22 => tmp_46_i,
        din23 => tmp_47_i,
        din24 => tmp_48_i,
        def => val_1_fu_817_p51,
        sel => s_mem_i_fu_641_p2,
        dout => val_1_fu_817_p53);

    flow_control_loop_pipe_sequential_init_U : component top_wrapper_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    s_fw_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                s_fw_fu_240 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln41_reg_1014 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0))) then 
                s_fw_fu_240 <= s_fw_7_fu_954_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln42_2_reg_1022 <= add_ln42_2_fu_695_p2;
                brmerge_not_i_reg_1018 <= brmerge_not_i_fu_659_p2;
                brmerge_not_i_reg_1018_pp0_iter1_reg <= brmerge_not_i_reg_1018;
                icmp_ln41_reg_1014 <= icmp_ln41_fu_631_p2;
                s_fw_4_reg_1008 <= ap_sig_allocacmp_s_fw_4;
                    select_ln42_reg_1027(1) <= select_ln42_fu_701_p3(1);
                val_1_reg_1037 <= val_1_fu_817_p53;
                val_1_reg_1037_pp0_iter1_reg <= val_1_reg_1037;
                val_reg_1032 <= val_fu_709_p53;
                val_reg_1032_pp0_iter1_reg <= val_reg_1032;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                cmp46_i_reg_1003 <= cmp46_i_fu_617_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0))) then
                trunc_ln2_reg_1042 <= add_ln42_1_fu_928_p2(63 downto 3);
            end if;
        end if;
    end process;
    select_ln42_reg_1027(0) <= '0';
    select_ln42_reg_1027(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to4, ap_done_pending_pp0, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to4 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln42_1_fu_928_p2 <= std_logic_vector(signed(sext_ln42_3_fu_925_p1) + signed(memory_load));
    add_ln42_2_fu_695_p2 <= std_logic_vector(signed(sext_ln42_1_fu_691_p1) + signed(p_cast_i_cast_fu_613_p1));
    add_ln42_fu_677_p2 <= std_logic_vector(unsigned(mul_ln40) + unsigned(sext_ln42_fu_673_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, m_axi_gmem1_0_AWREADY, ap_block_state5_io_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmem1_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, m_axi_gmem1_0_AWREADY, ap_block_state5_io_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((m_axi_gmem1_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, m_axi_gmem1_0_AWREADY, ap_block_state5_io_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmem1_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, m_axi_gmem1_0_BVALID, ap_block_state4_io_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_11001 <= (((m_axi_gmem1_0_BVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_io_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem1_0_BVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp4 <= ((m_axi_gmem1_0_BVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg));
    end process;

        ap_block_pp0_stage1_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, m_axi_gmem1_0_BVALID, ap_block_state4_io_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((m_axi_gmem1_0_BVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_io_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem1_0_BVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp4 <= ((m_axi_gmem1_0_BVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg));
    end process;


    ap_block_state4_io_grp2_assign_proc : process(m_axi_gmem1_0_WREADY, brmerge_not_i_reg_1018_pp0_iter1_reg)
    begin
                ap_block_state4_io_grp2 <= ((brmerge_not_i_reg_1018_pp0_iter1_reg = ap_const_lv1_1) and (m_axi_gmem1_0_WREADY = ap_const_logic_0));
    end process;


    ap_block_state5_io_grp1_assign_proc : process(m_axi_gmem1_0_WREADY, brmerge_not_i_reg_1018_pp0_iter1_reg)
    begin
                ap_block_state5_io_grp1 <= ((brmerge_not_i_reg_1018_pp0_iter1_reg = ap_const_lv1_1) and (m_axi_gmem1_0_WREADY = ap_const_logic_0));
    end process;


    ap_condition_323_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_01001_grp1)
    begin
                ap_condition_323 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1));
    end process;


    ap_condition_709_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_01001_grp2)
    begin
                ap_condition_709 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln41_reg_1014)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln41_reg_1014 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to4 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_s_fw_4_assign_proc : process(ap_CS_fsm_pp0_stage0, s_fw_fu_240, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_s_fw_4 <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_s_fw_4 <= s_fw_fu_240;
        end if; 
    end process;

    brmerge_not_i_fu_659_p2 <= (cmp32_i_fu_653_p2 and cmp31_i);
    cmp32_i_fu_653_p2 <= "1" when (signed(in_w_fu_647_p2) < signed(ap_const_lv32_D)) else "0";
    cmp46_i_fu_617_p2 <= "1" when (unsigned(s_iw) > unsigned(ap_const_lv4_5)) else "0";

    gmem1_blk_n_AW_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem1_0_AWREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem1_blk_n_AW <= m_axi_gmem1_0_AWREADY;
        else 
            gmem1_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, m_axi_gmem1_0_BVALID, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_grp4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg))) then 
            gmem1_blk_n_B <= m_axi_gmem1_0_BVALID;
        else 
            gmem1_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, m_axi_gmem1_0_WREADY, brmerge_not_i_reg_1018_pp0_iter1_reg, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage0_grp1, ap_block_pp0_stage1_grp2)
    begin
        if ((((brmerge_not_i_reg_1018_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((brmerge_not_i_reg_1018_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)))) then 
            gmem1_blk_n_W <= m_axi_gmem1_0_WREADY;
        else 
            gmem1_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln41_fu_631_p2 <= "1" when (signed(ap_sig_allocacmp_s_fw_4) < signed(ap_const_lv32_5)) else "0";
    in_w_fu_647_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_s_fw_4) + unsigned(zext_ln40_cast_fu_609_p1));
    m_axi_gmem1_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_ARID <= ap_const_lv1_0;
    m_axi_gmem1_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem1_0_AWADDR <= sext_ln42_2_fu_965_p1;
    m_axi_gmem1_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_AWID <= ap_const_lv1_0;
    m_axi_gmem1_0_AWLEN <= select_ln42_reg_1027(32 - 1 downto 0);
    m_axi_gmem1_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_AWUSER <= ap_const_lv1_0;

    m_axi_gmem1_0_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem1_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem1_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_11001_grp4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg))) then 
            m_axi_gmem1_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_0_RREADY <= ap_const_logic_0;

    m_axi_gmem1_0_WDATA_assign_proc : process(brmerge_not_i_reg_1018_pp0_iter1_reg, zext_ln51_fu_978_p1, zext_ln51_1_fu_986_p1, ap_condition_709, ap_condition_323)
    begin
        if ((brmerge_not_i_reg_1018_pp0_iter1_reg = ap_const_lv1_1)) then
            if ((ap_const_boolean_1 = ap_condition_323)) then 
                m_axi_gmem1_0_WDATA <= zext_ln51_1_fu_986_p1;
            elsif ((ap_const_boolean_1 = ap_condition_709)) then 
                m_axi_gmem1_0_WDATA <= zext_ln51_fu_978_p1;
            else 
                m_axi_gmem1_0_WDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axi_gmem1_0_WDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem1_0_WID <= ap_const_lv1_0;
    m_axi_gmem1_0_WLAST <= ap_const_logic_0;
    m_axi_gmem1_0_WSTRB <= ap_const_lv8_FF;
    m_axi_gmem1_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem1_0_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, brmerge_not_i_reg_1018_pp0_iter1_reg, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage0_11001_grp1, ap_block_pp0_stage1_11001_grp2)
    begin
        if ((((brmerge_not_i_reg_1018_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) or ((brmerge_not_i_reg_1018_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)))) then 
            m_axi_gmem1_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_cast_i_cast_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_cast_i),41));
    s_fw_5_fu_943_p2 <= std_logic_vector(unsigned(s_fw_4_reg_1008) + unsigned(ap_const_lv32_5));
    s_fw_6_fu_948_p3 <= 
        s_fw_5_fu_943_p2 when (cmp46_i_reg_1003(0) = '1') else 
        s_fw_4_reg_1008;
    s_fw_7_fu_954_p2 <= std_logic_vector(unsigned(s_fw_6_fu_948_p3) + unsigned(ap_const_lv32_1));
    s_mem_i_fu_641_p2 <= std_logic_vector(unsigned(trunc_ln41_fu_637_p1) + unsigned(mul_i));
    select_ln42_fu_701_p3 <= 
        ap_const_lv64_2 when (brmerge_not_i_fu_659_p2(0) = '1') else 
        ap_const_lv64_0;
        sext_ln42_1_fu_691_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_683_p3),41));

        sext_ln42_2_fu_965_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_reg_1042),64));

        sext_ln42_3_fu_925_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_2_reg_1022),64));

        sext_ln42_fu_673_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_665_p3),37));

        sext_ln51_1_fu_983_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(val_1_reg_1037_pp0_iter1_reg),45));

        sext_ln51_fu_975_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(val_reg_1032_pp0_iter1_reg),45));

    shl_ln_fu_665_p3 <= (in_w_fu_647_p2 & ap_const_lv1_0);
    tmp_fu_683_p3 <= (add_ln42_fu_677_p2 & ap_const_lv3_0);
    trunc_ln41_fu_637_p1 <= ap_sig_allocacmp_s_fw_4(5 - 1 downto 0);
    val_1_fu_817_p51 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    val_fu_709_p51 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    zext_ln40_cast_fu_609_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln40),32));
    zext_ln51_1_fu_986_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln51_1_fu_983_p1),64));
    zext_ln51_fu_978_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln51_fu_975_p1),64));
end behav;
