-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_wrapper_conv_Pipeline_VITIS_LOOP_41_1_VITIS_LOOP_42_2_VITIS_LOOP_43_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    filter2conv_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    filter2conv_empty_n : IN STD_LOGIC;
    filter2conv_read : OUT STD_LOGIC;
    filter2conv_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    filter2conv_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_17 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_16 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_15 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_14 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_13 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_12 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_11 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_10 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_9 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_8 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem : IN STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_35_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_35_out_ap_vld : OUT STD_LOGIC;
    filter_mem_34_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_34_out_ap_vld : OUT STD_LOGIC;
    filter_mem_33_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_33_out_ap_vld : OUT STD_LOGIC;
    filter_mem_32_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_32_out_ap_vld : OUT STD_LOGIC;
    filter_mem_31_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_31_out_ap_vld : OUT STD_LOGIC;
    filter_mem_30_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_30_out_ap_vld : OUT STD_LOGIC;
    filter_mem_29_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_29_out_ap_vld : OUT STD_LOGIC;
    filter_mem_28_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_28_out_ap_vld : OUT STD_LOGIC;
    filter_mem_27_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_27_out_ap_vld : OUT STD_LOGIC;
    filter_mem_26_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_26_out_ap_vld : OUT STD_LOGIC;
    filter_mem_25_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_25_out_ap_vld : OUT STD_LOGIC;
    filter_mem_24_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_24_out_ap_vld : OUT STD_LOGIC;
    filter_mem_23_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_23_out_ap_vld : OUT STD_LOGIC;
    filter_mem_22_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_22_out_ap_vld : OUT STD_LOGIC;
    filter_mem_21_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_21_out_ap_vld : OUT STD_LOGIC;
    filter_mem_20_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_20_out_ap_vld : OUT STD_LOGIC;
    filter_mem_19_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_19_out_ap_vld : OUT STD_LOGIC;
    filter_mem_18_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filter_mem_18_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of top_wrapper_conv_Pipeline_VITIS_LOOP_41_1_VITIS_LOOP_42_2_VITIS_LOOP_43_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal filter2conv_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal icmp_ln42_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_1299 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal idx_depth_fu_134 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln43_fu_1024_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal s_fw_fu_138 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln42_fu_694_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten_fu_142 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln42_1_fu_611_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal s_fh_fu_146 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln41_fu_668_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten48_fu_150 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln41_1_fu_593_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten48_load : STD_LOGIC_VECTOR (4 downto 0);
    signal filter_mem_18_fu_154 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_3_fu_974_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_48_fu_724_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal filter_mem_19_fu_158 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_2_fu_966_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_20_fu_162 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_5_fu_942_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_21_fu_166 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_4_fu_934_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_22_fu_170 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_7_fu_910_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_23_fu_174 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_6_fu_902_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_24_fu_178 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_9_fu_878_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_25_fu_182 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_8_fu_870_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_26_fu_186 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_11_fu_846_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_27_fu_190 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_10_fu_838_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_28_fu_194 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_13_fu_814_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_29_fu_198 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_12_fu_806_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_30_fu_202 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_15_fu_782_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_31_fu_206 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_14_fu_774_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_32_fu_210 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_17_fu_750_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_33_fu_214 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_16_fu_742_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_34_fu_218 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_1_fu_1006_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal filter_mem_35_fu_222 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln48_fu_998_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal add_ln42_3_fu_605_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln43_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln36_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln41_fu_638_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln36_fu_644_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln36_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln42_fu_675_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_shl_fu_706_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln41_fu_702_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_47_fu_714_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln42_fu_720_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal s_ich_mid2_fu_686_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln48_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_561 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component top_wrapper_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component top_wrapper_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    filter_mem_18_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_18_fu_154 <= filter_mem;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_0))) then 
                    filter_mem_18_fu_154 <= select_ln48_3_fu_974_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_19_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_19_fu_158 <= filter_mem_1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_0))) then 
                    filter_mem_19_fu_158 <= select_ln48_2_fu_966_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_20_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_20_fu_162 <= filter_mem_2;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_1))) then 
                    filter_mem_20_fu_162 <= select_ln48_5_fu_942_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_21_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_21_fu_166 <= filter_mem_3;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_1))) then 
                    filter_mem_21_fu_166 <= select_ln48_4_fu_934_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_22_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_22_fu_170 <= filter_mem_4;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_2))) then 
                    filter_mem_22_fu_170 <= select_ln48_7_fu_910_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_23_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_23_fu_174 <= filter_mem_5;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_2))) then 
                    filter_mem_23_fu_174 <= select_ln48_6_fu_902_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_24_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_24_fu_178 <= filter_mem_6;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_3))) then 
                    filter_mem_24_fu_178 <= select_ln48_9_fu_878_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_25_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_25_fu_182 <= filter_mem_7;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_3))) then 
                    filter_mem_25_fu_182 <= select_ln48_8_fu_870_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_26_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_26_fu_186 <= filter_mem_8;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_4))) then 
                    filter_mem_26_fu_186 <= select_ln48_11_fu_846_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_27_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_27_fu_190 <= filter_mem_9;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_4))) then 
                    filter_mem_27_fu_190 <= select_ln48_10_fu_838_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_28_fu_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_28_fu_194 <= filter_mem_10;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_5))) then 
                    filter_mem_28_fu_194 <= select_ln48_13_fu_814_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_29_fu_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_29_fu_198 <= filter_mem_11;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_5))) then 
                    filter_mem_29_fu_198 <= select_ln48_12_fu_806_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_30_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_30_fu_202 <= filter_mem_12;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_6))) then 
                    filter_mem_30_fu_202 <= select_ln48_15_fu_782_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_31_fu_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_31_fu_206 <= filter_mem_13;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_6))) then 
                    filter_mem_31_fu_206 <= select_ln48_14_fu_774_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_32_fu_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_32_fu_210 <= filter_mem_14;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_7))) then 
                    filter_mem_32_fu_210 <= select_ln48_17_fu_750_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_33_fu_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_33_fu_214 <= filter_mem_15;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (empty_48_fu_724_p2 = ap_const_lv4_7))) then 
                    filter_mem_33_fu_214 <= select_ln48_16_fu_742_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_34_fu_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_34_fu_218 <= filter_mem_16;
                elsif ((ap_const_boolean_1 = ap_condition_561)) then 
                    filter_mem_34_fu_218 <= select_ln48_1_fu_1006_p3;
                end if;
            end if; 
        end if;
    end process;

    filter_mem_35_fu_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    filter_mem_35_fu_222 <= filter_mem_17;
                elsif ((ap_const_boolean_1 = ap_condition_561)) then 
                    filter_mem_35_fu_222 <= select_ln48_fu_998_p3;
                end if;
            end if; 
        end if;
    end process;

    idx_depth_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    idx_depth_fu_134 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    idx_depth_fu_134 <= add_ln43_fu_1024_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten48_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln41_fu_587_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten48_fu_150 <= add_ln41_1_fu_593_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten48_fu_150 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln41_fu_587_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_142 <= select_ln42_1_fu_611_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_142 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    s_fh_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    s_fh_fu_146 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    s_fh_fu_146 <= select_ln41_fu_668_p3;
                end if;
            end if; 
        end if;
    end process;

    s_fw_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    s_fw_fu_138 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    s_fw_fu_138 <= select_ln42_fu_694_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln42_reg_1299 <= icmp_ln42_fu_599_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln41_1_fu_593_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten48_load) + unsigned(ap_const_lv5_1));
    add_ln41_fu_638_p2 <= std_logic_vector(unsigned(s_fh_fu_146) + unsigned(ap_const_lv2_1));
    add_ln42_3_fu_605_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv4_1));
    add_ln42_fu_675_p2 <= std_logic_vector(unsigned(select_ln36_fu_644_p3) + unsigned(ap_const_lv2_1));
    add_ln43_fu_1024_p2 <= std_logic_vector(unsigned(s_ich_mid2_fu_686_p3) + unsigned(ap_const_lv2_1));
    and_ln36_fu_662_p2 <= (xor_ln36_fu_651_p2 and icmp_ln43_fu_656_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, filter2conv_empty_n)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((filter2conv_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, filter2conv_empty_n)
    begin
                ap_block_pp0_stage0_11001 <= ((filter2conv_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, filter2conv_empty_n)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((filter2conv_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, filter2conv_empty_n)
    begin
                ap_block_pp0_stage0_subdone <= ((filter2conv_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_561_assign_proc : process(ap_enable_reg_pp0_iter1, empty_48_fu_724_p2)
    begin
                ap_condition_561 <= (not((empty_48_fu_724_p2 = ap_const_lv4_7)) and not((empty_48_fu_724_p2 = ap_const_lv4_6)) and not((empty_48_fu_724_p2 = ap_const_lv4_5)) and not((empty_48_fu_724_p2 = ap_const_lv4_4)) and not((empty_48_fu_724_p2 = ap_const_lv4_3)) and not((empty_48_fu_724_p2 = ap_const_lv4_2)) and not((empty_48_fu_724_p2 = ap_const_lv4_1)) and not((empty_48_fu_724_p2 = ap_const_lv4_0)) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_587_p2)
    begin
        if (((icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten48_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten48_fu_150)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten48_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten48_load <= indvar_flatten48_fu_150;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten_fu_142, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_142;
        end if; 
    end process;

    empty_47_fu_714_p2 <= std_logic_vector(unsigned(p_shl_fu_706_p3) - unsigned(zext_ln41_fu_702_p1));
    empty_48_fu_724_p2 <= std_logic_vector(unsigned(empty_47_fu_714_p2) + unsigned(zext_ln42_fu_720_p1));
    empty_fu_681_p2 <= (icmp_ln42_reg_1299 or and_ln36_fu_662_p2);

    filter2conv_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, filter2conv_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter2conv_blk_n <= filter2conv_empty_n;
        else 
            filter2conv_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    filter2conv_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter2conv_read <= ap_const_logic_1;
        else 
            filter2conv_read <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_18_out <= filter_mem_18_fu_154;

    filter_mem_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_18_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_19_out <= filter_mem_19_fu_158;

    filter_mem_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_19_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_20_out <= filter_mem_20_fu_162;

    filter_mem_20_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_20_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_21_out <= filter_mem_21_fu_166;

    filter_mem_21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_21_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_22_out <= filter_mem_22_fu_170;

    filter_mem_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_22_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_23_out <= filter_mem_23_fu_174;

    filter_mem_23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_23_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_24_out <= filter_mem_24_fu_178;

    filter_mem_24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_24_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_25_out <= filter_mem_25_fu_182;

    filter_mem_25_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_25_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_26_out <= filter_mem_26_fu_186;

    filter_mem_26_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_26_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_27_out <= filter_mem_27_fu_190;

    filter_mem_27_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_27_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_28_out <= filter_mem_28_fu_194;

    filter_mem_28_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_28_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_29_out <= filter_mem_29_fu_198;

    filter_mem_29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_29_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_30_out <= filter_mem_30_fu_202;

    filter_mem_30_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_30_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_30_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_31_out <= filter_mem_31_fu_206;

    filter_mem_31_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_31_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_32_out <= filter_mem_32_fu_210;

    filter_mem_32_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_32_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_32_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_33_out <= filter_mem_33_fu_214;

    filter_mem_33_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_33_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_33_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_34_out <= filter_mem_34_fu_218;

    filter_mem_34_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_34_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_34_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filter_mem_35_out <= filter_mem_35_fu_222;

    filter_mem_35_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln41_fu_587_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln41_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_mem_35_out_ap_vld <= ap_const_logic_1;
        else 
            filter_mem_35_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln41_fu_587_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten48_load = ap_const_lv5_12) else "0";
    icmp_ln42_fu_599_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv4_6) else "0";
    icmp_ln43_fu_656_p2 <= "1" when (idx_depth_fu_134 = ap_const_lv2_2) else "0";
    icmp_ln48_fu_730_p2 <= "1" when (s_ich_mid2_fu_686_p3 = ap_const_lv2_0) else "0";
    p_shl_fu_706_p3 <= (select_ln41_fu_668_p3 & ap_const_lv2_0);
    s_ich_mid2_fu_686_p3 <= 
        ap_const_lv2_0 when (empty_fu_681_p2(0) = '1') else 
        idx_depth_fu_134;
    select_ln36_fu_644_p3 <= 
        ap_const_lv2_0 when (icmp_ln42_reg_1299(0) = '1') else 
        s_fw_fu_138;
    select_ln41_fu_668_p3 <= 
        add_ln41_fu_638_p2 when (icmp_ln42_reg_1299(0) = '1') else 
        s_fh_fu_146;
    select_ln42_1_fu_611_p3 <= 
        ap_const_lv4_1 when (icmp_ln42_fu_599_p2(0) = '1') else 
        add_ln42_3_fu_605_p2;
    select_ln42_fu_694_p3 <= 
        add_ln42_fu_675_p2 when (and_ln36_fu_662_p2(0) = '1') else 
        select_ln36_fu_644_p3;
    select_ln48_10_fu_838_p3 <= 
        filter_mem_27_fu_190 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    select_ln48_11_fu_846_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_26_fu_186;
    select_ln48_12_fu_806_p3 <= 
        filter_mem_29_fu_198 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    select_ln48_13_fu_814_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_28_fu_194;
    select_ln48_14_fu_774_p3 <= 
        filter_mem_31_fu_206 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    select_ln48_15_fu_782_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_30_fu_202;
    select_ln48_16_fu_742_p3 <= 
        filter_mem_33_fu_214 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    select_ln48_17_fu_750_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_32_fu_210;
    select_ln48_1_fu_1006_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_34_fu_218;
    select_ln48_2_fu_966_p3 <= 
        filter_mem_19_fu_158 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    select_ln48_3_fu_974_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_18_fu_154;
    select_ln48_4_fu_934_p3 <= 
        filter_mem_21_fu_166 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    select_ln48_5_fu_942_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_20_fu_162;
    select_ln48_6_fu_902_p3 <= 
        filter_mem_23_fu_174 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    select_ln48_7_fu_910_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_22_fu_170;
    select_ln48_8_fu_870_p3 <= 
        filter_mem_25_fu_182 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    select_ln48_9_fu_878_p3 <= 
        filter2conv_dout when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter_mem_24_fu_178;
    select_ln48_fu_998_p3 <= 
        filter_mem_35_fu_222 when (icmp_ln48_fu_730_p2(0) = '1') else 
        filter2conv_dout;
    xor_ln36_fu_651_p2 <= (icmp_ln42_reg_1299 xor ap_const_lv1_1);
    zext_ln41_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln41_fu_668_p3),4));
    zext_ln42_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln42_fu_694_p3),4));
end behav;
