// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_wrapper_top_wrapper,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=14,HLS_SYN_DSP=0,HLS_SYN_FF=169034,HLS_SYN_LUT=88262,HLS_VERSION=2024_2}" *)

module top_wrapper (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axi_control_r_AWVALID,
        s_axi_control_r_AWREADY,
        s_axi_control_r_AWADDR,
        s_axi_control_r_WVALID,
        s_axi_control_r_WREADY,
        s_axi_control_r_WDATA,
        s_axi_control_r_WSTRB,
        s_axi_control_r_ARVALID,
        s_axi_control_r_ARREADY,
        s_axi_control_r_ARADDR,
        s_axi_control_r_RVALID,
        s_axi_control_r_RREADY,
        s_axi_control_r_RDATA,
        s_axi_control_r_RRESP,
        s_axi_control_r_BVALID,
        s_axi_control_r_BREADY,
        s_axi_control_r_BRESP,
        s_axi_gmem3_AWVALID,
        s_axi_gmem3_AWREADY,
        s_axi_gmem3_AWADDR,
        s_axi_gmem3_WVALID,
        s_axi_gmem3_WREADY,
        s_axi_gmem3_WDATA,
        s_axi_gmem3_WSTRB,
        s_axi_gmem3_ARVALID,
        s_axi_gmem3_ARREADY,
        s_axi_gmem3_ARADDR,
        s_axi_gmem3_RVALID,
        s_axi_gmem3_RREADY,
        s_axi_gmem3_RDATA,
        s_axi_gmem3_RRESP,
        s_axi_gmem3_BVALID,
        s_axi_gmem3_BREADY,
        s_axi_gmem3_BRESP,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_ADDR_WIDTH = 6;
parameter    C_S_AXI_GMEM3_DATA_WIDTH = 32;
parameter    C_S_AXI_GMEM3_ADDR_WIDTH = 16;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_R_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_GMEM3_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input   s_axi_control_r_AWVALID;
output   s_axi_control_r_AWREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_AWADDR;
input   s_axi_control_r_WVALID;
output   s_axi_control_r_WREADY;
input  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_WDATA;
input  [C_S_AXI_CONTROL_R_WSTRB_WIDTH - 1:0] s_axi_control_r_WSTRB;
input   s_axi_control_r_ARVALID;
output   s_axi_control_r_ARREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_ARADDR;
output   s_axi_control_r_RVALID;
input   s_axi_control_r_RREADY;
output  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_RDATA;
output  [1:0] s_axi_control_r_RRESP;
output   s_axi_control_r_BVALID;
input   s_axi_control_r_BREADY;
output  [1:0] s_axi_control_r_BRESP;
input   s_axi_gmem3_AWVALID;
output   s_axi_gmem3_AWREADY;
input  [C_S_AXI_GMEM3_ADDR_WIDTH - 1:0] s_axi_gmem3_AWADDR;
input   s_axi_gmem3_WVALID;
output   s_axi_gmem3_WREADY;
input  [C_S_AXI_GMEM3_DATA_WIDTH - 1:0] s_axi_gmem3_WDATA;
input  [C_S_AXI_GMEM3_WSTRB_WIDTH - 1:0] s_axi_gmem3_WSTRB;
input   s_axi_gmem3_ARVALID;
output   s_axi_gmem3_ARREADY;
input  [C_S_AXI_GMEM3_ADDR_WIDTH - 1:0] s_axi_gmem3_ARADDR;
output   s_axi_gmem3_RVALID;
input   s_axi_gmem3_RREADY;
output  [C_S_AXI_GMEM3_DATA_WIDTH - 1:0] s_axi_gmem3_RDATA;
output  [1:0] s_axi_gmem3_RRESP;
output   s_axi_gmem3_BVALID;
input   s_axi_gmem3_BREADY;
output  [1:0] s_axi_gmem3_BRESP;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_ready;
reg    ap_done;
reg    ap_idle;
wire   [63:0] filter_val;
wire   [63:0] memory;
wire   [44:0] memory_in_q0;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
wire    gmem1_0_ARREADY;
wire    gmem1_0_RVALID;
wire   [63:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
wire   [1:0] gmem1_0_BRESP;
wire   [0:0] gmem1_0_BID;
wire   [0:0] gmem1_0_BUSER;
wire    gmem2_0_AWREADY;
wire    gmem2_0_WREADY;
wire    gmem2_0_ARREADY;
wire    gmem2_0_RVALID;
wire   [31:0] gmem2_0_RDATA;
wire    gmem2_0_RLAST;
wire   [0:0] gmem2_0_RID;
wire   [8:0] gmem2_0_RFIFONUM;
wire   [0:0] gmem2_0_RUSER;
wire   [1:0] gmem2_0_RRESP;
wire    gmem2_0_BVALID;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WVALID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WDATA;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_BREADY;
wire   [11:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_address0;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_ce0;
wire   [44:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_d0;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_we0;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WDATA;
wire   [7:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_start;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_done;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_ready;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_idle;
wire    dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_continue;
reg   [2:0] loop_dataflow_input_count;
reg   [2:0] loop_dataflow_output_count;
wire   [2:0] bound_minus_1;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 3'd0;
#0 loop_dataflow_output_count = 3'd0;
end

top_wrapper_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

top_wrapper_control_r_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_R_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_R_DATA_WIDTH ))
control_r_s_axi_U(
    .AWVALID(s_axi_control_r_AWVALID),
    .AWREADY(s_axi_control_r_AWREADY),
    .AWADDR(s_axi_control_r_AWADDR),
    .WVALID(s_axi_control_r_WVALID),
    .WREADY(s_axi_control_r_WREADY),
    .WDATA(s_axi_control_r_WDATA),
    .WSTRB(s_axi_control_r_WSTRB),
    .ARVALID(s_axi_control_r_ARVALID),
    .ARREADY(s_axi_control_r_ARREADY),
    .ARADDR(s_axi_control_r_ARADDR),
    .RVALID(s_axi_control_r_RVALID),
    .RREADY(s_axi_control_r_RREADY),
    .RDATA(s_axi_control_r_RDATA),
    .RRESP(s_axi_control_r_RRESP),
    .BVALID(s_axi_control_r_BVALID),
    .BREADY(s_axi_control_r_BREADY),
    .BRESP(s_axi_control_r_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .filter_val(filter_val),
    .memory(memory)
);

top_wrapper_gmem3_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_GMEM3_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_GMEM3_DATA_WIDTH ))
gmem3_s_axi_U(
    .AWVALID(s_axi_gmem3_AWVALID),
    .AWREADY(s_axi_gmem3_AWREADY),
    .AWADDR(s_axi_gmem3_AWADDR),
    .WVALID(s_axi_gmem3_WVALID),
    .WREADY(s_axi_gmem3_WREADY),
    .WDATA(s_axi_gmem3_WDATA),
    .WSTRB(s_axi_gmem3_WSTRB),
    .ARVALID(s_axi_gmem3_ARVALID),
    .ARREADY(s_axi_gmem3_ARREADY),
    .ARADDR(s_axi_gmem3_ARADDR),
    .RVALID(s_axi_gmem3_RVALID),
    .RREADY(s_axi_gmem3_RREADY),
    .RDATA(s_axi_gmem3_RDATA),
    .RRESP(s_axi_gmem3_RRESP),
    .BVALID(s_axi_gmem3_BVALID),
    .BREADY(s_axi_gmem3_BREADY),
    .BRESP(s_axi_gmem3_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .memory_in_address0(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_address0),
    .memory_in_ce0(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_ce0),
    .memory_in_q0(memory_in_q0)
);

top_wrapper_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWVALID),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWADDR),
    .I_CH0_AWLEN(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWLEN),
    .I_CH0_WVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WVALID),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WDATA),
    .I_CH0_WSTRB(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WSTRB),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_BREADY)
);

top_wrapper_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARVALID),
    .I_CH0_ARREADY(gmem2_0_ARREADY),
    .I_CH0_ARADDR(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARADDR),
    .I_CH0_ARLEN(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARLEN),
    .I_CH0_RVALID(gmem2_0_RVALID),
    .I_CH0_RREADY(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_RREADY),
    .I_CH0_RDATA(gmem2_0_RDATA),
    .I_CH0_RFIFONUM(gmem2_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem2_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem2_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem2_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

top_wrapper_dataflow_in_loop_VITIS_LOOP_92_1_1 dataflow_in_loop_VITIS_LOOP_92_1_1_U0(
    .m_axi_gmem2_0_AWVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(gmem2_0_RLAST),
    .m_axi_gmem2_0_RID(gmem2_0_RID),
    .m_axi_gmem2_0_RFIFONUM(gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(gmem2_0_RUSER),
    .m_axi_gmem2_0_RRESP(gmem2_0_RRESP),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .filter_val1(filter_val),
    .memory_in_address0(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_address0),
    .memory_in_ce0(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_ce0),
    .memory_in_d0(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_d0),
    .memory_in_q0(memory_in_q0),
    .memory_in_we0(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_memory_in_we0),
    .img_0(loop_dataflow_input_count),
    .m_axi_gmem1_0_AWVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(gmem1_0_AWREADY),
    .m_axi_gmem1_0_AWADDR(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(gmem1_0_WREADY),
    .m_axi_gmem1_0_WDATA(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(1'b0),
    .m_axi_gmem1_0_ARADDR(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(1'b0),
    .m_axi_gmem1_0_RREADY(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(64'd0),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(9'd0),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(gmem1_0_BVALID),
    .m_axi_gmem1_0_BREADY(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(gmem1_0_BRESP),
    .m_axi_gmem1_0_BID(gmem1_0_BID),
    .m_axi_gmem1_0_BUSER(gmem1_0_BUSER),
    .memory(memory),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .memory_ap_vld(1'b1),
    .ap_start(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_start),
    .filter_val1_ap_vld(1'b1),
    .img_0_ap_vld(1'b0),
    .ap_done(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_done),
    .ap_ready(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_ready),
    .ap_idle(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_idle),
    .ap_continue(dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        loop_dataflow_input_count <= 3'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_ready == 1'b1) & (ap_start == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 3'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_ready == 1'b1) & (ap_start == 1'b1))) begin
            loop_dataflow_input_count <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        loop_dataflow_output_count <= 3'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_continue == 1'b1) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 3'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_continue == 1'b1) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 3'd0;
        end
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 3'd0) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_idle == 1'b1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_ready == 1'b1) & (ap_start == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bound_minus_1 = (3'd5 - 3'd1);

assign dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_start = ap_start;

assign gmem1_0_BID = 1'd0;

assign gmem1_0_BRESP = 2'd0;

assign gmem1_0_BUSER = 1'd0;

assign gmem2_0_RID = 1'd0;

assign gmem2_0_RLAST = 1'b0;

assign gmem2_0_RRESP = 2'd0;

assign gmem2_0_RUSER = 1'd0;

assign dataflow_in_loop_VITIS_LOOP_92_1_1_U0_ap_continue = 1'b1;

endmodule //top_wrapper
